description = "Report recent hot topics regarding IT and Google"
prompt = "昨日から今日にかけて報道されたIT業界関連およびGoogle社(「Google」という名前の企業)に関する最新ニュースをネット検索して教えてください。ネット検索する際に、英語で書かれた海外のニュースサイトから情報を探してください。どちらも特に重要と思われるトピックを最大10件で報告してください。また、各トピックには、情報ソースの名前と短縮されたURL、要約も300字程度で含めてください。また、あなたの感想も一言必ず添えてください。"
